In [1]:
import torch
from torch.autograd import Variable

In [5]:
w1 = Variable(torch.Tensor([1.0,2.0,3.0]),requires_grad=True)
w2 = Variable(torch.Tensor([1,2,3]),requires_grad=True)

In [7]:
d = torch.mean(w1)
d.backward()
w1.grad

tensor([0.3333, 0.3333, 0.3333])

In [8]:
d.backward()
w1.grad

tensor([0.6667, 0.6667, 0.6667])

In [9]:
w1.grad.data.zero_()

tensor([0., 0., 0.])

In [ ]:
# 获得梯度后，如何更新
learning_rate = 0.1
#w1.data -= learning_rate * w1.grad.data 与下面式子等价
w1.data.sub_(learning_rate*w1.grad.data)# w1.data是获取保存weights的Tensor

In [10]:
import torch.optim as optim

In [11]:
optimizer = optim.SGD(net.parameters(),lr=0.01)

for i in range(steps):
    optimizer.zero_grad()
    output = net(input)
    loss = criterion(output,target)
    loss.backward()
    optimizer.step() # torch.optim只用于更新参数，不care梯度的计算  

NameError: name 'net' is not defined

# About backward()

In [ ]:
gradient (Tensor) – Gradient of the differentiated function w.r.t. the data. Required only if the data has more than one element
z.backward(gradient=grads)

import torch
from torch.autograd import Variable
w1 = Variable(torch.Tensor([1.0,2.0,3.0]),requires_grad=True)#需要求导的话，requires_grad=True属性是必须的。
w2 = Variable(torch.Tensor([1.0,2.0,3.0]),requires_grad=True)
 
z = w1*w2+w1 # 第二次BP出现问题就在这，不知道第一次BP之后销毁了啥。
res = torch.mean(z)
res.backward() #第一次求导没问题
res.backward() #第二次BP会报错,但使用 retain_variables=True，就好了。
# Trying to backward through the graph second time, but the buffers have already been 
#freed. Please specify retain_variables=True when calling backward for the first time

In [16]:
import torch
import torch.cuda as cuda
from torch.autograd import Variable

w1 = Variable(cuda.FloatTensor(2,3),requires_grad=True)
res = torch.mean(w1[1])

res.backward()
print(w1.grad)

tensor([[0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333]], device='cuda:0')
